micronaut:
  application:
    name: book-management

#  datasources:
#      default:
#          url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#          url: ${JDBC_URL:`jdbc:h2:./db`}
#          url: ${JDBC_URL:`jdbc:h2:./db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#          username: ${JDBC_USER:sa}
#          password: ${JDBC_PASSWORD:""}
#          driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  datasources:
      default:
          url: jdbc:sqlite:book.db
            driverClassName: org.sqlite.JDBC
#  jpa:
#      default:
#          packages-to-scan:
#              - 'book.management.entity'
#          properties:
#              hibernate:
#                  hbm2ddl:
#                      auto: update
#                  show_sql: true
